# Generated by Django 3.0.8 on 2020-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201105_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
